# Generated by Django 5.1.1 on 2024-09-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveillance", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aianalysis",
            old_name="created_at",
            new_name="timestamp",
        ),
        migrations.AlterField(
            model_name="aianalysis",
            name="analysis_result",
            field=models.TextField(),
        ),
    ]
