# Generated by Django 5.1.1 on 2024-09-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveillance", "0002_rename_created_at_aianalysis_timestamp_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_file", models.FileField(upload_to="videos/")),
                (
                    "gps_latitude",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "gps_longitude",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
